### ISSUE TITLE
请问http-flv如何播放？

### ISSUE THREAD

**Issue by hipitt** [q191201771/yet#2]
推流到yet, 推送地址：rtmp://192.168.1.2/p/p
尝试出用VLC播放RTMP的地址是rtmp://192.168.1.2/p/p?&vhost=192.168.1.2
请问RTMP的播放地址规则是什么样的？

是否在用rtmp播放的同时，也可以用http-flv播放? 播放的地址规则是什么样的？
没尝试出来... 
@q191201771

**Comment by q191201771** [comment]
可以试试这样： http://192.168.1.2:8080/p/p.flv
另外，关于rtmp服务器这块，我目前新写了一个Go语言版本的项目lal，搞yet这个项目的精力转移到那边去了，感兴趣的话可以关注一下，github地址如下，谢谢。
https://github.com/q191201771/lal

对了，lal那个项目目前已经大体完成rtmp相关的基础功能，计划这周末或者下周末加入http-flv。
@hipitt

**Comment by hipitt** [comment]
没播出来，等大佬更新了再看：-）
